'use strict'

var util = require('util');
var assert = require('assert');
var fs = require('fs');
var os = require('os');
var uuid = require('node-uuid');

var EvaluatorUtil = require('io-event-reactor/ioReactor').EvaluatorUtil;
var IoEvent = require('io-event-reactor-plugin-support').IoEvent;
var IoReactorService = require('io-event-reactor');


// setup our tmpdir where event info will be echo'd too
var targetTmpDir = os.tmpdir() + "/" + uuid.v4();
fs.mkdir(targetTmpDir, function(err) {
    if (err) {
        throw err;
    }
});

var logger = function(severity, origin, message) {
    if (severity != 'verbose') {
        console.log(severity + ' ' + origin + ' ' + message);
    }
};

var errorCallback = function(message,error) {
    console.log("ERROR-CALLBACK! " + message + ' ' + error);
};


/**
* Generates a IoEventService configuration based around a MockMonitorPlugin and the ShellExecReactorPlugin
*
* @param shellConfigs - contains 2 props, processCommand and processArgs
* @param evaluatorFunction - evaluator function that will gate the mock IoEvents triggered via 'monitorTriggerConfigs' and let them flow (or not) to the ShellExec reactor
* @param monitorTriggerConfigs array of MockMonitorPlugin monitorTrigger config objects, these trigger fake IoEvents through the IoReactor frameworks
*/
function generateConfig(shellConfig, evaluatorFunction, monitorTriggerConfigs) {

    return {
            logFunction: logger,
            errorCallback: errorCallback,

            ioReactors: [

                  {
                      id: "ioReactor-test1",

                      // mock monitor, will trigger mocked IoEvents according to monitorTriggerConfigs
                      monitor: {
                          plugin: "io-event-reactor/test/mockMonitor",
                          config: {
                              monitorTriggers: monitorTriggerConfigs
                          }
                      },

                      // evaluators, we have one that will gate the fake IoEvents
                      // generated by monitorTriggerConfigs
                      evaluators: [
                          {
                              evaluator: evaluatorFunction,
                              reactors: ['shellExec1']
                          }
                      ],

                      // reactors, we have one 'mysql1', inserts
                      // them into the target database
                      reactors: [

                          { id: "shellExec1",
                            plugin: "../../",
                            config: {
                                    statefulProcessCommandProxy: {
                                        config: {
                                            name: "ioReactor-test1-shell-exec",
                                            max: 1,
                                            min: 1,
                                            idleTimeoutMS: 120000,
                                            logFunction: logger,
                                            processCommand: shellConfig.processCommand,
                                            processArgs:  shellConfig.processArgs,
                                            processRetainMaxCmdHistory : 10,
                                            processCwd : './',
                                            validateFunction: function(processProxy) {
                                                return processProxy.isValid();
                                            }
                                        }
                                    },
                                    commandTemplates: shellConfig.commandTemplates,
                                    commandGenerator: shellConfig.commandGenerator
                                }
                          },
                      ]

                  }

             ]
        };
};

var shellConfigs = {
    windows: {
        processCommand: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
        processArgs: ['-Command', '-'],
        commandTemplates: [
            '"{{{ioEvent.eventType}}}" | Out-File -FilePath '+targetTmpDir+'/{{ioEvent.uuid}}'
        ],
        commandGenerator: function(ioEvent) {
          return [('"'+ioEvent.eventType+'" | Out-File -FilePath '+targetTmpDir+'/'+ioEvent.uuid)];
        }
    },
    nix: {
        processCommand: '/bin/bash',
        processArgs: ['-s'],
        commandTemplates: [
            'echo "{{{ioEvent.eventType}}}" > '+targetTmpDir+'/{{ioEvent.uuid}}'
        ],
        commandGenerator: function(ioEvent) {
          return [('echo "'+ioEvent.eventType+'" > '+targetTmpDir+'/gen_'+ioEvent.uuid)];
        }
    }
};



describe('shell-exec-reactor-test', function() {

    it('Start a mock monitor, validate that a few simple events pass the monitor -> evaluator -> ShellExec reactor engine flow', function(done) {

        this.timeout(5000);

        var isWin = /^win/.test(process.platform);

        // chose the right config based on platform
        var shellConfig = (isWin ? shellConfigs['windows'] : shellConfigs['nix']);

        // generate our config, only matching add/unlink events for specific filenames
        var mockConfig = generateConfig(shellConfig,
                                        EvaluatorUtil.regex(['add','unlink'],'.*testFile\\d+','ig'),
                                        [
                                            // generate an add, should react to this
                                            { eventGenerator: function() {
                                                               return new IoEvent('add','/tmp/testFile1',{size:100},null);
                                                              },
                                              timeout: 100
                                            },

                                            // generate an unlink, should react to this
                                            { eventGenerator: function() {
                                                               return new IoEvent('unlink','/tmp/testFile1',{size:100},null);
                                                              },
                                              timeout: 100
                                            },

                                            // generate an unlinkDir, should not react to this
                                            { eventGenerator: function() {
                                                               return new IoEvent('unlinkDir','/tmp/testFile1',{size:100},null);
                                                              },
                                              timeout: 100
                                            },

                                            // generate an change for diff file, should not react to this
                                            { eventGenerator: function() {
                                                               return new IoEvent('change','/tmp/testFile1',{size:100},null);
                                                              },
                                              timeout: 100
                                            },

                                            // generate an add for diff file (letter, not number), should not react to this
                                            { eventGenerator: function() {
                                                               return new IoEvent('add','/tmp/testFileA',{size:100},null);
                                                              },
                                              timeout: 100
                                            },

                                            // generate an add, should react to this
                                            { eventGenerator: function() {
                                                               return new IoEvent('add','/tmp/testFile100',{size:100},null);
                                                              },
                                              timeout: 100
                                            },
                                        ]);


        // start the reactor
        var reactor = new IoReactorService(mockConfig);

        // check that both tables contains 6 events...
        // (2 commands generated per event X 3 reacted events)
        setTimeout(function() {

            fs.readdir(targetTmpDir,function(err,files){
                if (err) {
                    done("Error validating files from dir: " + targetTmpDir + " error:" + err);
                }
                assert.equal(files.length,6);
                done();
            });

        },2000);

    });

});
